# Generated by Django 4.2.5 on 2023-09-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofertas',
            options={'verbose_name_plural': 'Ofertas'},
        ),
    ]
