# Generated by Django 4.2.5 on 2023-09-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_alter_ofertas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='datecompleted',
            field=models.DateTimeField(null=True),
        ),
    ]
