# Generated by Django 4.2.4 on 2023-11-01 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ofertas', '0004_ofertas_lat_ofertas_lng_alter_ofertas_datecompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertas',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ofertas',
            name='datecompleted',
        ),
        migrations.AddField(
            model_name='ofertas',
            name='aceptada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ofertas',
            name='aceptada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas_aceptadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
