# Generated by Django 4.2.7 on 2023-11-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0006_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='fecha_terminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ofertas',
            name='terminada',
            field=models.BooleanField(default=False),
        ),
    ]
